### ISSUE TITLE
장바구니 담기 기능이 정상적으로 동작하지 않음

### ISSUE THREAD

**Issue by d-h-k** [d-h-k/just-board#65]
### 아이템 상세페이지(item/[#id]) 에서 에러나면 무조건 회원정보가 없다고 리다이렉트 시키는중
- 스프링시큐리티 문제인듯 403 에러가 무조건 발생해서 로직에 들어가지 않음

## 해결
- 두가지 문제가 있었는데
### 2) cors 설정을 추가해서 문제 해결

**Comment by d-h-k** [comment]
```
There was an unexpected error (type=Internal Server Error, status=500). For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8  use the javac flag -parameters.; nested exception is java.lang.IllegalStateException: For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8  use the javac flag -parameters. org.springframework.dao.InvalidDataAccessApiUsageException: For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8  use the javac flag -parameters.; nested exception is java.lang.IllegalStateException: For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8  use the javac flag -parameters.  at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:371)  at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:235)  
```

```
예기치 않은 오류가 발생했습니다(유형=내부 서버 오류, 상태=500). 명명된 매개변수가 있는 쿼리의 경우 메소드 매개변수의 이름을 제공해야 합니다. 쿼리 메소드 매개변수에 @Param을 사용하거나 Java 8의 경우 javac 플래그 -parameters를 사용합니다.; 중첩 예외는 java.lang.IllegalStateException입니다. 명명된 매개변수가 있는 쿼리의 경우 메소드 매개변수에 대한 이름 제공을 사용해야 합니다. 쿼리 메서드 매개변수에 @Param을 사용하거나 Java 8의 경우 javac 플래그 -parameters를 사용합니다. org.springframework.dao.InvalidDataAccessApiUsageException: 명명된 매개변수가 있는 쿼리의 경우 메소드 매개변수의 이름을 제공해야 합니다. 쿼리 메소드 매개변수에 @Param을 사용하거나 Java 8의 경우 javac 플래그 -parameters를 사용합니다.; 중첩 예외는 java.lang.IllegalStateException입니다. 명명된 매개변수가 있는 쿼리의 경우 메소드 매개변수에 대한 이름 제공을 사용해야 합니다. 쿼리 메서드 매개변수에 @Param을 사용하거나 Java 8의 경우 javac 플래그 -parameters를 사용합니다. org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:371) org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect).java:23
```

**Comment by d-h-k** [comment]
해결함 여기링크 참조하고
 https://zzang9ha.tistory.com/357

**Comment by d-h-k** [comment]
- 추가한부분

```java
@Param("cartId")
```

- 기존
```java
@Query(value = "select new com.justboard.justboard.cart.CartDetailDto" +
            "(ci.id, i.itemName, i.price, ci.count, im.imgUrl) " +
            "from CartItem ci, ItemImg im " +
            "join ci.item i " +
            "where ci.cart.id = :cartId " +
            "and im.item.id = ci.item.id " +
            "and im.repimg = 'Y' " +
            "order by ci.createdTime desc")
    List<CartDetailDto> findCartDetailDtoList(Long cartId);

```

- 수정
```java@Query(value = "select new com.justboard.justboard.cart.CartDetailDto" +
            "(ci.id, i.itemName, i.price, ci.count, im.imgUrl) " +
            "from CartItem ci, ItemImg im " +
            "join ci.item i " +
            "where ci.cart.id = :cartId " +
            "and im.item.id = ci.item.id " +
            "and im.repimg = 'Y' " +
            "order by ci.createdTime desc")
    List<CartDetailDto> findCartDetailDtoList(@Param("cartId") Long cartId);

```

**Comment by d-h-k** [comment]
https://dev-pengun.tistory.com/entry/Spring-Boot-CORS-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
